services:
  app: &app_base
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - EDITOR=vi
    env_file: app.env
    volumes:
      - ./:/home/appuser/home_dashboard
      - ./.docker/.bundle:/home/appuser/home_dashboard/.bundle
    restart: unless-stopped
    depends_on:
      - db
      - redis
  db:
    image: postgres:17
    env_file: app.env
    volumes:
      - ./.docker/postgres/:/var/lib/postgresql/data
    restart: unless-stopped
  sidekiq:
    <<: *app_base
    command: sh -c "rm -f tmp/pids/sidekiq.pid && bundle exec sidekiq"
    ports: []
  redis:
    image: redis:latest
    expose:
      - "6379:6379"
    volumes:
      - ./.docker/redis/data:/data
